### PR TITLE
Fix all caps for title

### LINKED ISSUE #4: Make nginx all caps in the title header

### PR DESCRIPTION
**Pull request by famasboy888**
This will close #4

### CODE REVIEW

**Review by famasboy888 — COMMENTED** [review]
Cool. Its all caps now

File: frontend/src/components/Navbar.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ const Navbar = () => {
             <div className="container">
                 <Link to="/">
                     <h1>End-to-End CICD</h1>
-                    <h2>with Nginx</h2>
+                    <h2>with NGINX</h2>
```
Comment (famasboy888) [inline frontend/src/components/Navbar.js:9]: Why are we  making this all caps again?

Comment (famasboy888) [reply frontend/src/components/Navbar.js:9]: Coz it looks cool. Lmao 😄

Comment (famasboy888) [reply frontend/src/components/Navbar.js:9]: Yeap. Fine!
